spring.application.name=service-Login

# Puerto del servicio
server.port=8081

# Configuración PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/login_db
spring.datasource.username=postgres
spring.datasource.password=FarmaExpres

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect